# Generated by Django 5.0.1 on 2024-02-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
