# Generated by Django 5.0.1 on 2024-02-17 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_brand_remove_product_categories_alter_product_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categories',
            new_name='category',
        ),
    ]
