# Generated by Django 5.0.1 on 2024-02-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_categories_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, to='products.tag', verbose_name='Etiquetas'),
        ),
    ]
