# Generated by Django 5.0 on 2024-01-11 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_project_options_project_information_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='information',
            new_name='link',
        ),
    ]
