# Generated by Django 5.0.1 on 2024-06-13 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Equipo')),
                ('shield', models.ImageField(upload_to='shields/', verbose_name='Escudo')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journey', models.CharField(max_length=100, verbose_name='Jornada')),
                ('result', models.CharField(max_length=10, verbose_name='Resultado')),
                ('date', models.DateTimeField(verbose_name='Fecha')),
                ('local_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_matches', to='matches.team', verbose_name='Equipo Local')),
                ('visiting_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visiting_matches', to='matches.team', verbose_name='Equipo Visitante')),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
                'ordering': ['-date'],
            },
        ),
    ]
