# Generated by Django 5.0.1 on 2024-06-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_alter_match_options_alter_match_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='shield',
            field=models.ImageField(default='escudo_vacio.jpg', upload_to='shields/', verbose_name='Escudo'),
        ),
    ]
