# Generated by Django 5.0.1 on 2024-06-13 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_alter_match_date_alter_match_result'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-journey'], 'verbose_name': 'Partido', 'verbose_name_plural': 'Partidos'},
        ),
    ]
