# Generated by Django 5.0.1 on 2024-06-14 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('soccer_number', models.PositiveSmallIntegerField(verbose_name='Dorsal')),
                ('birthdate', models.DateField(verbose_name='Fecha de nacimiento')),
                ('profile', models.ImageField(blank=True, null=True, upload_to='jugadores/', verbose_name='Perfil')),
                ('age', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Edad')),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games_played', models.PositiveSmallIntegerField(default=0, verbose_name='Partido Jugados')),
                ('minutes_played', models.PositiveSmallIntegerField(default=0, verbose_name='Minutos')),
                ('goals', models.PositiveSmallIntegerField(default=0, verbose_name='Goles')),
                ('yellow_cards', models.PositiveSmallIntegerField(default=0, verbose_name='Tarjeas Amarillas')),
                ('red_cards', models.PositiveSmallIntegerField(default=0, verbose_name='Tarjetas Rojas')),
                ('player', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='players.players', verbose_name='Estadísticas')),
            ],
        ),
    ]
