# Generated by Django 5.0.1 on 2024-06-14 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='player',
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['-name'], 'verbose_name': 'Jugador', 'verbose_name_plural': 'Jugadores'},
        ),
        migrations.RemoveField(
            model_name='player',
            name='games_played',
        ),
        migrations.RemoveField(
            model_name='player',
            name='goals',
        ),
        migrations.RemoveField(
            model_name='player',
            name='minutes_played',
        ),
        migrations.RemoveField(
            model_name='player',
            name='red_cards',
        ),
        migrations.RemoveField(
            model_name='player',
            name='yellow_cards',
        ),
        migrations.AddField(
            model_name='player',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Edad'),
        ),
        migrations.AddField(
            model_name='player',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='player',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellidos'),
        ),
        migrations.AddField(
            model_name='player',
            name='name',
            field=models.CharField(default='Jugador', max_length=100, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='player',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='jugadores/', verbose_name='Perfil'),
        ),
        migrations.AddField(
            model_name='player',
            name='soccer_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Dorsal'),
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games_played', models.PositiveSmallIntegerField(default=0, verbose_name='Partido Jugados')),
                ('minutes_played', models.PositiveSmallIntegerField(default=0, verbose_name='Minutos')),
                ('goals', models.PositiveSmallIntegerField(default=0, verbose_name='Goles')),
                ('yellow_cards', models.PositiveSmallIntegerField(default=0, verbose_name='Tarjeas Amarillas')),
                ('red_cards', models.PositiveSmallIntegerField(default=0, verbose_name='Tarjetas Rojas')),
                ('player', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='players.player', verbose_name='Estadísticas')),
            ],
        ),
        migrations.DeleteModel(
            name='Players',
        ),
    ]
