# Generated by Django 5.0.1 on 2024-06-15 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_position_remove_player_player_alter_player_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statistic',
            options={'verbose_name': 'Estadística', 'verbose_name_plural': 'Estadísticas'},
        ),
    ]
