# Generated by Django 5.0.1 on 2024-06-17 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_alter_player_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='player',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='players.player', verbose_name='Estadísticas'),
        ),
    ]
