# Generated by Django 5.0.1 on 2024-06-17 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_player_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='alias',
            field=models.CharField(max_length=100, verbose_name='Alias'),
        ),
        migrations.AlterField(
            model_name='player',
            name='birthdate',
            field=models.DateField(default=datetime.date(1990, 1, 1), verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='player',
            name='soccer_number',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Dorsal'),
        ),
    ]
