# Generated by Django 5.0.1 on 2024-06-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_alter_player_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='profile',
            field=models.ImageField(blank=True, default='players/usuario.png', null=True, upload_to='players/', verbose_name='Perfil'),
        ),
    ]
